### ISSUE TITLE
nice skid token logger

### ISSUE THREAD

**Issue by highday144hz** [9-judge/stacey-nuker#1]
Lmao nice try using a skid youtube token logger like we finna fall for that

**Comment by 9-judge** [comment]
no shit nigga who names a nuker 'stacey/tacey nuker' and who tf gives people an actual nuker LMAO

**Comment by highday144hz** [comment]
> no shit nigga who names a nuker 'stacey/tacey nuker' and who tf gives people an actual nuker LMAO
